### PR TITLE
feat(ngMocks): add expectRoute and whenRoute shortcuts with colon param matching

### PR DESCRIPTION
**Pull request by dmaloneycalu**
<- commit message ->
feat(ngMocks): add expectRoute and whenRoute shortcuts with colon param matching

Add whenRoute method to $httpBackend to support matching similar to API backends, which
handles responses based on the query to a particular route. Also includes params in the respond
function to give access to both query params and route colon delimited values.

This is a feature request and is not associated with any open issue
<- end commit message ->

@vokal/web @scottferg 
This is for company review. Before this can be merged into Angular, we'll have to [sign the CLA](https://github.com/vokal/angular.js/blob/master/CONTRIBUTING.md#-signing-the-cla) as a company since the contribution is coming from Vokal. Also, the merge commit message needs to be the same as above per Angular's [contribution requirements](https://github.com/vokal/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines). Let me know if any of the wording should be changed prior to merging this PR.

### CODE REVIEW

**Comment by jrit** [comment]
That commit message seems a little terse for introducing this as a new feature to someone that won't have a background on the development. Is it that the commit message preference is terseness but when you open the PR you will provide the additional background and examples that would be needed for someone to evaluate the merits of the feature without digging into the code?

**Comment by jrit** [comment]
Does the spec have 100% coverage?

**Comment by dmaloneycalu** [comment]
@jrit 

The commit message is a bit terse, but the presumption is that the documentation updates in the code should be sufficient, an example should be included in the PR to be a bit more indicative of our reasons for the feature request. 

Angular's test suite does not produce coverage reports unfortunately so I can't say for certain. But all tests in the suite are passing, both unit and e2e.

**Comment by jrit** [comment]
Sounds good.

**Comment by dmaloneycalu** [comment]
I'll get a demo piece typed out prior to this being merged.

**Comment by dmaloneycalu** [comment]
Here's an [example page](https://gist.github.com/dmaloneycalu/cb258e2f3b987fd687b2) that reflects one of our use cases for the feature (paged API responses).

**Comment by dmaloneycalu** [comment]
@Tathanen @StoicJester @cmdadabo

Anyone want to weigh in with critique on the feature/demo page?

**Comment by Tathanen** [comment]
NOPE

**Comment by jrit** [comment]
LGTM

**Pull request merged**
